### ISSUE TITLE
Not up to date

### ISSUE THREAD

**Issue by Xwilarg** [DeathMiner/Epitech-2021-Timeline#3]
Hi,
The timelist isn't up to date.
Is it please possible to update it ?

**Comment by demaisj** [comment]
Hey,
The planning for semester 4 is currently not available on the intranet so I can't update the timeline yet. I think we'll need to wait until the end of the c++ pool.
Have a good day ;)

**Comment by Xwilarg** [comment]
Oh, sorry for the useless issue.
